services:
  - type: web
    name: marvel-app
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: APP_NAME
        value: Marvel
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://marvel-app.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: mysql
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: marvel_laravel
      - key: DB_USERNAME
        value: marvel_user
      - key: DB_PASSWORD
        sync: fromService
        serviceName: mysql

  - type: pserv
    name: mysql
    runtime: docker
    envVars:
      - key: image
        value: mysql:8.0
      - key: MYSQL_ROOT_PASSWORD
        generateValue: true
      - key: MYSQL_DATABASE
        value: marvel_laravel
      - key: MYSQL_USER
        value: marvel_user
      - key: MYSQL_PASSWORD
        generateValue: true
    disk:
      name: mysql_data
      mountPath: /var/lib/mysql
      sizeGB: 10