services:
  - type: web
    name: marvel-app
    runtime: docker
    dockerfilePath: ./vendor/laravel/sail/runtimes/8.1/Dockerfile
    dockerContext: .
    buildCommand: |
      docker build -t marvel-app \
        --build-arg WWWGROUP=1000 \
        --build-arg WWWUSER=1000 \
        -f ./vendor/laravel/sail/runtimes/8.1/Dockerfile .
    envVars:
      - key: WWWUSER
        value: "1000"
      - key: LARAVEL_SAIL
        value: "1"
      - key: APP_PORT
        value: "8000"
      # [Include all your other environment variables]
      - key: APP_NAME
        value: Marvel
      - key: APP_ENV
        value: production
      # ... (rest of your environment variables)

  - type: pserv
    name: mysql
    runtime: docker
    envVars:
      - key: image
        value: mysql:8.0
      - key: MYSQL_ROOT_PASSWORD
        generateValue: true
      - key: MYSQL_DATABASE
        value: marvel_laravel
      - key: MYSQL_USER
        value: marvel_user
      - key: MYSQL_PASSWORD
        generateValue: true
      - key: MYSQL_ALLOW_EMPTY_PASSWORD
        value: "yes"
    disk:
      name: mysql_data
      mountPath: /var/lib/mysql
      sizeGB: 10

  - type: pserv
    name: redis
    runtime: docker
    envVars:
      - key: image
        value: redis:alpine
    disk:
      name: redis_data
      mountPath: /data
      sizeGB: 1

  - type: pserv
    name: mailhog
    runtime: docker
    envVars:
      - key: image
        value: mailhog/mailhog:latest
      - key: MH_UI_WEB_PORT
        value: "8025"
        
